abstract class AppStates{}
class AppInitialState extends AppStates{}
class GetUserSuccessState extends AppStates{}
class ChangeEyeState extends AppStates{}
class UserSingOutSuccessState extends AppStates{}
class GetUserErrorState extends AppStates{}
class ChangeBottomNavState extends AppStates{}
class GetCategoryLoadingState extends AppStates{}
class GetSingleCategoryLoadingState extends AppStates{}
class GetCategorySuccessState extends AppStates{}
class GetSingleCategorySuccessState extends AppStates{}
class GetCategoryErrorState extends AppStates{}
class GetSingleCategoryErrorState extends AppStates{}
class GetProductLoadingState extends AppStates{}
class GetProductSuccessState extends AppStates{}
class GetProductErrorState extends AppStates{}
class GetBannerLoadingState extends AppStates{}
class GetBannerSuccessState extends AppStates{}
class GetBannerErrorState extends AppStates{}
class PickProfileImageSuccessState extends AppStates{}
class UploadProfileImageSuccessState extends AppStates{}
class UploadProfileImageErrorState extends AppStates{}
class UpdateUserErrorState extends AppStates{}
class UpdateUserSucessState extends AppStates{}